name: "build-rogd"
replicaCount: 1

images:
  PullSecrets: 
    name: kartingreg
  repository: genesisproject.azurecr.io/build-rogd
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

volume:
  - name: build-rogd-volume
    mountPath: /usr/src/app/dist/config/
    secretName: azure-secret 
    shareName: system-genesis/build-rogd
    type: azurefile

config:
  configmaps: 
    name: build-rogd
